<a href="https://colab.research.google.com/github/tawsif113/ml-python-foundations/blob/main/week1/Math_intutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Math intuition + mini-project wrap-up

Vectors

In [107]:
import numpy as np

vector = np.array([2,4,6])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(vector)
print(matrix)

[2 4 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [108]:
values = np.array([10, 20, 20, 30, 100])

print("Mean:", np.mean(values))
print("Median:", np.median(values))
print("Variance:", np.var(values))
print("Std Dev:", np.std(values))

Mean: 36.0
Median: 20.0
Variance: 1064.0
Std Dev: 32.61901286060018


Dot Product

In [109]:
features = np.array([2,3,4])
weights = np.array([0.5, 1.0, 2.0])


score = np.dot(features, weights)
print("Dot product score:", score)

Dot product score: 12.0


In [110]:
survived = 342
total = 891

prob_survived = survived / total
print("Survival probability:", prob_survived)

Survival probability: 0.3838383838383838


In [112]:
import pandas as pd

df = pd.DataFrame({
    "math":[80,90],
    "english":[70,85]
})
marks = pd.DataFrame([[80,90],[70,85]])
weights = pd.Series([0.6,0.4])
print(marks.dot(weights))



0    84.0
1    76.0
dtype: float64
