<a href="https://colab.research.google.com/github/tawsif113/ml-python-foundations/blob/main/week1/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Day 1

Import numpy

In [ ]:
import numpy as np

print(np.__version__)

2.0.2


Create Arrays

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print(arr1,type(arr1),arr1.shape,sep=" ")

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)


Create Matrix

In [ ]:
matrix = np.array([
    [1,2,3],
    ["A","B","C"],
    [10.5,10.9,1.2]
])

print(matrix)
print(matrix.shape)
print(type(matrix))
print(matrix.ndim)

[['1' '2' '3']
 ['A' 'B' 'C']
 ['10.5' '10.9' '1.2']]
(3, 3)
<class 'numpy.ndarray'>
2


Create Special Arrays

In [ ]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
full = np.full((2, 2), 7)
identity = np.eye(3)

print(zeros)
print(ones)
print(full)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Indexing & Slicing

In [ ]:
range_arr = np.arange(0, 10, 2)
line_arr = np.linspace(0, 10, 5)

print(range_arr)
print(line_arr)

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
x = np.linspace(0,2*np.pi, 100)
y = np.sin(x)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix[0,:])
print(matrix[:,0])
print(matrix[0,0])
print(matrix[1,2])
print(matrix[0:2,1:3])

[1 2 3]
[1 4 7]
1
6
[[2 3]
 [5 6]]


Boolean Masking, Filtering Data

In [ ]:
matrix[matrix > 5]

array([6, 7, 8, 9])

Vectorization

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print(arr1 + arr2)
print(arr2 - arr1)
print(arr1 * 2)
print(arr1 / 2)
print(arr1 ** 2)
print(arr1 + 5)

[11 22 33 44]
[ 9 18 27 36]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[6 7 8 9]


Aggregation

In [ ]:
arr = np.array([5, 10, 15, 20])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

50
12.5
20
5
5.5901699437494745


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np.sum(matrix))
print(np.sum(matrix, axis=0))  # column-wise
print(np.sum(matrix, axis=1))  # row-wise

21
[5 7 9]
[ 6 15]


Reshape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print(arr)
print(reshaped)
print(reshaped.shape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(arr.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


##Practice Tasks

In [ ]:
arr = np.linspace(1,10,10)
print(arr.shape)
print(arr.ndim)
print(type(arr))

(10,)
1
<class 'numpy.ndarray'>


In [ ]:
arr = np.linspace(1,9,9)
print(arr.reshape(3,3))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
matrix = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])

print(matrix[0,:])
print(matrix[:,1])
print(matrix[-1,-1])
print(matrix[1:3,0:2])

[11 12 13]
[12 22 32]
33
[[21 22]
 [31 32]]


In [ ]:
arr = np.array([2, 4, 6, 8])
print(arr.sum())
print(arr.mean(), arr.max(), arr.min(), sep="\n")

20
5.0
8
2


In [ ]:
arr = np.arange(1,13)
print(arr.reshape(3,4))
print(arr.reshape(2,6))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## NOTES

A NumPy array is a powerful, high-performance, multidimensional array object (officially called an ndarray) used for numerical computing in Python. It provides an efficient way to store and manipulate large datasets, especially for mathematical, scientific, and data science operations.

There are some differences between list and np arrays
like a list [1,2,3] + [4,5,6] will concatanate
but Numpy arrays will do element wise operation same operation will be [5,7,9] this is called Vectorization

Shape means the dimensions of the Numpy array for example for 2x3 arrays shape will be (2,3)

For aggregations we used Axis=0 or Axis=1, Here Axis is called the row or columns

#Numpy Day 2

Boolean masking

In [2]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])

print(arr > 12)
print(arr[arr > 12])
print(arr[arr % 10 == 0])

[False False  True  True  True]
[15 20 25]
[10 20]


In [ ]:
arr = np.array([3, 8, 12, 17, 21, 26])

filtered = arr[(arr > 10) & (arr < 25)]
print(filtered)

[12 17 21]


Broadcasting

In [ ]:
arr = np.array([1, 2, 3])
print(arr + 10)
print(arr * 5)

[11 12 13]
[ 5 10 15]


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix + 10)

[[11 12 13]
 [14 15 16]]


In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np.sum(matrix, axis=0))  # column-wise
print(np.sum(matrix, axis=1))  # row-wise

print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))

[5 7 9]
[ 6 15]
[2.5 3.5 4.5]
[2. 5.]


In [ ]:
arr1 = np.array([1, 2, 4])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1, arr2)))
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[1 2 4 4 5 6]
[[1 2 4]
 [4 5 6]]
[1 2 4 4 5 6]


random arrays

In [ ]:
np.random.seed(42)

rand_arr = np.random.randint(1, 100, size=10)
print(rand_arr)

rand_matrix = np.random.randint(1, 10, size=(3, 3))
print(rand_matrix)

[52 93 15 72 61 21 83 87 75 75]
[[8 5 4]
 [8 8 3]
 [6 5 2]]


##Practice tasks

In [ ]:
arr = np.array([4, 7, 10, 15, 18, 21, 24])

print(arr[arr > 10])
print(arr[arr%2==0])
print(arr[(arr > 9) & (arr<21)])

[15 18 21 24]
[ 4 10 18 24]
[10 15 18]


In [ ]:
random_matrix = np.random.randint(1,50,size=(4,4))
print(random_matrix)
print(random_matrix.max())
print(random_matrix.min())
print(random_matrix.sum(axis=1))
print(random_matrix.mean(axis=0))

[[15 47 44  3]
 [37  7 21  9]
 [39 18  4 25]
 [14  9 26  2]]
47
2
[109  74  86  51]
[26.25 20.25 23.75  9.75]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a+b)
print(a*b)
print(a+100)

[11 22 33]
[10 40 90]
[101 102 103]


In [5]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(matrix[1,:])
print(matrix[:,2])
print(matrix[1,])

[40 50 60]
[30 60 90]
[40 50 60]


In [20]:
row = matrix.shape[0]
col = matrix.shape[1]
mid_x = row//2
mid_y = col//2
print(matrix[mid_x,mid_y])

print(matrix[-2:,:])

3 3
50
[[40 50 60]
 [70 80 90]]


In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1, arr2)))
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
