<a href="https://colab.research.google.com/github/tawsif113/ml-python-foundations/blob/main/week2/ml_workflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ML WORKFLOW

##A beginner-friendly version:

define problem

load dataset

inspect data

choose features and target

split train/test

train model

predict

evaluate

improve

In [113]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [118]:
iris = load_iris()

print(type(iris))
print(iris.keys())

<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [120]:
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target,name="target")
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [121]:
print(X.shape)
print(X.columns)
print(X.describe())
print(y.value_counts())

(150, 4)
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  
target
0    50
1    50
2    50
Name: count, dtype: i

In [122]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [123]:
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [124]:
y_pred = model.predict(X_test)

print(y_pred[:10])
print(y_test.iloc[:10].values)

[1 0 2 1 1 0 1 2 1 1]
[1 0 2 1 1 0 1 2 1 1]


In [125]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [126]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



**Interpret simply** <br>
Model Achieved 100% -_- <br>
Confusion matrix shows correct prediction.
This is a classification problem

What is supervised learning?

Supervised learning is when a machine learning model learns from data that already has the correct answers.
The model studies examples of inputs and their correct outputs so it can learn a pattern and make predictions on new data.

Example:
If we show the model many flowers with their measurements and species names, it can learn to predict the species of a new flower.

What are features?

Features are the input variables used by the model to make predictions.
They describe the data.

Example in the Iris dataset:

sepal length

sepal width

petal length

petal width

These measurements are the features.

What is a target?

The target is the value we want the model to predict.

In the Iris dataset, the target is the flower species:

setosa

versicolor

virginica

So the model uses the features to predict the target.

What is train/test split?

Train/test split means dividing the dataset into two parts:

Training set → used to teach the model

Test set → used to check how well the model performs on new data

This helps us see if the model actually learned patterns or just memorized the data.

What does fit() do?

fit() is the step where the model learns from the training data.

The algorithm looks at the features and targets and tries to find patterns that connect them.

Example:

model.fit(X_train, y_train)

This is where the model is trained.

What does predict() do?

predict() uses the trained model to guess the target values for new data.

Example:

model.predict(X_test)

It takes the feature values and predicts which class they belong to.

What confused me today?

What confused me today was understanding how the dataset is structured when loading it from sklearn.
At first it wasn’t obvious that load_iris() returns a special object containing data, targets, feature names, and descriptions instead of a normal DataFrame.
I also had to understand how the features and target relate to the model training process.